name: bot
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.3
  sembast: ^3.5.0
  path_provider: ^2.1.1
  http: ^1.1.0
  flutter_dotenv: ^5.1.0
  intl: ^0.18.1
  uuid: ^4.1.0
  sembast_web: ^2.1.3
  rive: ^0.13.20

flutter:
  uses-material-design: true
  assets:
    - assets/.env
    - assets/chatlogo.jpg
    - assets/animations/bot.riv
