name: news_portal_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # HTTP API
  http: ^1.2.0

  # Declarative navigation
  go_router: ^14.2.0

  # Local NoSQL DB for caching stories (Web)
  sembast: ^3.6.0
  sembast_web: ^2.0.0        # Web support for Sembast

  # JSON serialization and Equatable
  json_annotation: ^4.9.0
  equatable: ^2.0.5

  # Localization
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Code generation
  build_runner: ^2.5.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
